// Original localized radio writing. No simulation state or RNG is consumed here.
export const EN_BATTLE_LINES = Object.freeze({
  terran: {
    start: ['Formation ready. Keep your coffee secured.', 'Armor checked. Discipline is our second shield.'],
    kill: ['Target neutralized. Paperwork can wait.', 'Clean shot, fleet. Put that one in the report.'],
    loss: ['We lost a ship. Cover the survivors!', 'Close the gap. Nobody gets left without cover.'],
    cast: ['Special systems cleared. Hold on to your mugs.', 'Executing the maneuver. Yes, we rehearsed this one.'],
    sudden: ['No more repairs. Make every hull count.', 'Sudden death. Time to finish the shift.'],
    victory: ['Mission complete. Coffee is on me.', 'Count our ships before you start celebrating.'],
    defeat: ['Retreat is an order too. We will come back prepared.', 'Save the lessons. We will rebuild the fleet.'],
    draw: ['A draw. There is no box for that on my form.'],
  },
  vorrax: {
    start: ['The swarm scents fresh metal.', 'Many wings. One hunger. No table reservation.'],
    kill: ['Crunchy armor. Empty center.', 'The hive thanks you for this meal.'],
    loss: ['One voice falls silent. A thousand still answer.', 'Guard the brood! Hunger can wait.'],
    cast: ['The hive sings. The prey tastes fear.', 'Follow the scent. The feast begins.'],
    sudden: ['Flesh will mend no more. Bite carefully.', 'The final hunger is upon us.'],
    victory: ['The hive thrives. Leave room for dessert.', 'We feast! Nobody eats the transport ship.'],
    defeat: ['Hunger learns. The swarm returns.', 'This prey had teeth. We will remember.'],
    draw: ['Two hungry swarms. No dessert.'],
  },
  lumen: {
    start: ['Tune the crystals. The void awaits our light.', 'We are light. Please keep a safe distance anyway.'],
    kill: ['Another silence in the cosmic score.', 'The target saw the light. Rather closely.'],
    loss: ['One light fades. Carry its memory.', 'Guard the choir. Our harmony grows fragile.'],
    cast: ['The phase opens. Breathe between moments.', 'Perfect resonance. This is not a decoration.'],
    sudden: ['Even light has limits. Focus our radiance.', 'Twilight has arrived ahead of schedule.'],
    victory: ['The choir endures. Let our light lead us home.', 'A radiant victory. We can polish the crystals later.'],
    defeat: ['Light scatters. It does not vanish.', 'Our next song will have a different arrangement.'],
    draw: ['Two lights in balance. A rest between songs.'],
  },
  ferrix: {
    start: ['Fleet synchronized. Experimental humor enabled.', 'Scrap probability: high. Source: undetermined.'],
    kill: ['Target converted to inventory.', 'Threat removed. Storage space reclaimed.'],
    loss: ['Unit lost. That was not in the budget.', 'Redundancy reduced. Protect the remaining cores.'],
    cast: ['Protocol running. Do not switch off the universe.', 'Tactical update applied. No restart required.'],
    sudden: ['Regeneration unavailable. Support ticket cancelled.', 'Time remaining: insufficient. Optimize completion.'],
    victory: ['Victory confirmed. Simulated smile successful.', 'Satisfactory result. Commendations issued in binary.'],
    defeat: ['Failure recorded. Learning preserved.', 'Plan revised. Delete item: lose again.'],
    draw: ['Null result. At least nobody divided by zero.'],
  },
  astral: {
    start: ['Chart the orbits. Destiny accepts corrections.', 'We bend space. Fleet regulations still apply.'],
    kill: ['One fewer orbit on the chart.', 'The target chose the wrong center of gravity.'],
    loss: ['A beacon is lost. Hold our course.', 'Not every future can be saved. Protect this one.'],
    cast: ['Geometry has just picked a side.', 'Fold the field. Mind the edges.'],
    sudden: ['The horizon closes. Choose our next step.', 'Time has a gravity of its own.'],
    victory: ['We have reached the future we charted.', 'Crossing complete. You may release the instruments.'],
    defeat: ['We will chart the constellation again.', 'This route closes. Others remain.'],
    draw: ['Two orbits. One unlikely equilibrium.'],
  },
});

export const ES_BATTLE_LINES = Object.freeze({
  terran: {
    start: ['Formación lista. Sujeten bien el café.', 'Blindaje revisado. La disciplina es nuestro segundo escudo.'],
    kill: ['Objetivo neutralizado. El papeleo puede esperar.', 'Buen disparo, flota. Anótenlo en el informe.'],
    loss: ['Perdimos una nave. ¡Cubran a los supervivientes!', 'Cierren la formación. Nadie se queda sin cobertura.'],
    cast: ['Sistemas especiales listos. Sujeten las tazas.', 'Ejecutando maniobra. Esta sí la ensayamos.'],
    sudden: ['Ya no hay reparaciones. Cada casco cuenta.', 'Muerte súbita. Hora de terminar el turno.'],
    victory: ['Misión cumplida. Yo invito al café.', 'Cuenten las naves antes de celebrar.'],
    defeat: ['Retirarse también es una orden. Volveremos preparados.', 'Conserven lo aprendido. Reconstruiremos la flota.'],
    draw: ['Empate. Mi formulario no tiene esa casilla.'],
  },
  vorrax: {
    start: ['El enjambre huele metal fresco.', 'Muchas alas. La misma hambre. Ninguna reserva de mesa.'],
    kill: ['Crujiente por fuera. Chatarra por dentro.', 'La colmena agradece la comida.'],
    loss: ['Una voz calla. Mil siguen respondiendo.', '¡Protejan a las crías! El hambre puede esperar.'],
    cast: ['La colmena canta. La presa saborea el miedo.', 'Sigan el aroma. Comienza el banquete.'],
    sudden: ['La carne ya no se regenera. Muerdan con cuidado.', 'Ha llegado el hambre final.'],
    victory: ['La colmena prospera. Dejen sitio para el postre.', '¡Vencimos! Nadie se come la nave de transporte.'],
    defeat: ['El hambre aprende. El enjambre regresa.', 'Esta presa tenía dientes. Lo recordaremos.'],
    draw: ['Dos hambres. Ningún postre.'],
  },
  lumen: {
    start: ['Afinemos los cristales. El vacío espera nuestra luz.', 'Somos luz. Aun así, respeten la distancia de seguridad.'],
    kill: ['Otro silencio en la partitura del cosmos.', 'El objetivo vio la luz. Demasiado cerca.'],
    loss: ['Un brillo se apaga. Conservemos su memoria.', 'Protejan el coro. La armonía se debilita.'],
    cast: ['Se abre la fase. Respiren entre los instantes.', 'Resonancia perfecta. Esto no es decoración.'],
    sudden: ['Incluso la luz tiene límites. Concentren el brillo.', 'El crepúsculo llegó antes de lo previsto.'],
    victory: ['El coro perdura. Que la luz nos lleve a casa.', 'Victoria radiante. Puliremos los cristales después.'],
    defeat: ['La luz se dispersa, pero no desaparece.', 'Nuestra próxima canción tendrá otro arreglo.'],
    draw: ['Dos luces en equilibrio. Una pausa en la canción.'],
  },
  ferrix: {
    start: ['Flota sincronizada. Humor experimental activado.', 'Probabilidad de chatarra: alta. Origen: por determinar.'],
    kill: ['Objetivo convertido en inventario.', 'Amenaza eliminada. Espacio de almacenamiento liberado.'],
    loss: ['Unidad perdida. No estaba en el presupuesto.', 'Redundancia reducida. Protejan los núcleos restantes.'],
    cast: ['Ejecutando protocolo. No apague el universo.', 'Actualización táctica aplicada. No hace falta reiniciar.'],
    sudden: ['Regeneración no disponible. Soporte cancelado.', 'Queda poco tiempo. Optimicen la conclusión.'],
    victory: ['Victoria confirmada. Sonrisa simulada con éxito.', 'Resultado satisfactorio. Felicitaciones en binario.'],
    defeat: ['Fallo registrado. Aprendizaje conservado.', 'Plan revisado. Eliminar tarea: volver a perder.'],
    draw: ['Resultado nulo. Al menos nadie dividió entre cero.'],
  },
  astral: {
    start: ['Tracen las órbitas. El destino acepta correcciones.', 'Doblamos el espacio. Las reglas de la flota siguen vigentes.'],
    kill: ['Una órbita menos en el mapa.', 'El objetivo eligió el centro de gravedad equivocado.'],
    loss: ['Perdimos un faro. Mantengan el rumbo.', 'No podemos salvar cada futuro. Protejan este.'],
    cast: ['La geometría acaba de tomar partido.', 'Plieguen el campo. Cuidado con los bordes.'],
    sudden: ['El horizonte se cierra. Elijan el siguiente paso.', 'El tiempo también tiene gravedad.'],
    victory: ['Llegamos al futuro que trazamos.', 'Travesía terminada. Pueden soltar los instrumentos.'],
    defeat: ['Volveremos a trazar la constelación.', 'Esta ruta se cierra. Quedan otras.'],
    draw: ['Dos órbitas. Un equilibrio improbable.'],
  },
});
