import { test } from 'node:test';
import assert from 'node:assert/strict';
import { mkdtemp, rm } from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import net from 'node:net';
import { once } from 'node:events';
import { startServer } from '../../server/index.js';
import { createTestClient } from './helpers.js';

test('durable profile survives a server restart and health reports storage mode without private data', async (t) => {
  const dataDir = await mkdtemp(path.join(os.tmpdir(), 'fe-lifecycle-'));
  let server;
  t.after(async () => { await server?.close(); await rm(dataDir, { recursive: true, force: true }); });
  server = await startServer({ port: 0, secure: false, profileDataDir: dataDir });
  let base = `http://127.0.0.1:${server.port}`;
  const created = await fetch(`${base}/api/profile`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' });
  const profile = (await created.json()).profile;
  const cookie = created.headers.get('set-cookie').split(';')[0];
  const health = await (await fetch(`${base}/health`)).json();
  assert.equal(health.ok, true);
  assert.equal(health.capabilities.profilePersistence, 'durable');
  assert.equal(JSON.stringify(health).includes(dataDir), false);
  assert.equal(JSON.stringify(health).includes(profile.id), false);
  await server.close();
  server = await startServer({ port: 0, secure: false, profileDataDir: dataDir, ephemeralData: true });
  base = `http://127.0.0.1:${server.port}`;
  const reopened = await fetch(`${base}/api/profile`, { headers: { Cookie: cookie } });
  assert.equal((await reopened.json()).profile.id, profile.id);
  assert.equal((await (await fetch(`${base}/health`)).json()).capabilities.profilePersistence, 'ephemeral');
});

test('shutdown immediately stops accepting clients, drains WS, and bounds unfinished HTTP before closing SQLite', async (t) => {
  const server = await startServer({ port: 0, host: '127.0.0.1', secure: false });
  t.after(() => server.close());
  const base = `http://127.0.0.1:${server.port}`;
  const response = await fetch(`${base}/api/profile`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: '{}' });
  const id = (await response.json()).profile.id;
  const ws = createTestClient(`ws://127.0.0.1:${server.port}`, 'shutdown');
  await ws.open; await ws.hello();
  const socket = net.connect(server.port, '127.0.0.1');
  t.after(async () => { socket.destroy(); await ws.close(); await server.close(); });
  await once(socket, 'connect');
  const requestStarted = once(server.httpServer, 'request');
  socket.write('POST /api/profile HTTP/1.1\r\nHost: localhost\r\nContent-Type: application/json\r\nContent-Length: 100\r\n\r\n{');
  await requestStarted;
  const at = Date.now();
  const closing = server.close();
  assert.equal(server.close(), closing, 'shutdown is idempotent');
  assert.equal(server.httpServer.listening, false, 'listener closes before DB');
  assert.equal(server.profiles.getProfile(id).id, id, 'DB remains open while requests drain');
  await assert.rejects(fetch(`${base}/health`));
  assert.equal((await ws.waitClosed()).code, 1001);
  await closing;
  assert.ok(Date.now() - at < 5000, 'partial requests cannot hold shutdown indefinitely');
  assert.equal(server.wss.clients.size, 0);
  assert.throws(() => server.profiles.getProfile(id));
  const connections = await new Promise((resolve, reject) => server.httpServer.getConnections((error, n) => error ? reject(error) : resolve(n)));
  assert.equal(connections, 0);
});
